create or replace procedure SMAZ_VSECHNY_TABULKY AS
-- pokud v logu bude uvedeno, ze nektery objekt nebyl zrusen, protoze na nej jiny jeste existujici objekt stavi, spust proceduru opakovane, dokud se nezrusi vse
begin
  for iRec in 
    (select distinct OBJECT_TYPE, OBJECT_NAME,
      'drop '||OBJECT_TYPE||' "'||OBJECT_NAME||'"'||
      case OBJECT_TYPE when 'TABLE' then ' cascade constraints purge' else ' ' end as PRIKAZ
    from USER_OBJECTS where OBJECT_NAME not in ('SMAZ_VSECHNY_TABULKY', 'VYPNI_CIZI_KLICE', 'ZAPNI_CIZI_KLICE', 'VYMAZ_DATA_VSECH_TABULEK')
    ) loop
        begin
          dbms_output.put_line('Prikaz: '||irec.prikaz);
        execute immediate iRec.prikaz;
        exception
          when others then dbms_output.put_line('NEPOVEDLO SE!');
        end;
      end loop;
end;
/

create or replace procedure VYPNI_CIZI_KLICE as 
begin
  for cur in (select CONSTRAINT_NAME, TABLE_NAME from USER_CONSTRAINTS where CONSTRAINT_TYPE = 'R' ) 
  loop
    execute immediate 'alter table '||cur.TABLE_NAME||' modify constraint "'||cur.CONSTRAINT_NAME||'" DISABLE';
  end loop;
end VYPNI_CIZI_KLICE;
/


create or replace procedure ZAPNI_CIZI_KLICE as 
begin
  for cur in (select CONSTRAINT_NAME, TABLE_NAME from USER_CONSTRAINTS where CONSTRAINT_TYPE = 'R' ) 
  loop
    execute immediate 'alter table '||cur.TABLE_NAME||' modify constraint "'||cur.CONSTRAINT_NAME||'" enable validate';
  end loop;
end ZAPNI_CIZI_KLICE;
/

create or replace procedure VYMAZ_DATA_VSECH_TABULEK is
begin
  -- Vymazat data vsech tabulek
  VYPNI_CIZI_KLICE;
  for v_rec in (select distinct TABLE_NAME from USER_TABLES)
  loop
    execute immediate 'truncate table '||v_rec.TABLE_NAME||' drop storage';
  end loop;
  ZAPNI_CIZI_KLICE;
  
  -- Nastavit vsechny sekvence od 1
  for v_rec in (select distinct SEQUENCE_NAME  from USER_SEQUENCES)
  loop
    execute immediate 'alter sequence '||v_rec.SEQUENCE_NAME||' restart start with 1';
  end loop;
end VYMAZ_DATA_VSECH_TABULEK;
/

prompt #------------------------#
prompt #- Zrusit stare tabulky -#
prompt #------------------------#

exec SMAZ_VSECHNY_TABULKY;



-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1536
--   at:        2019-05-06 14:10:37 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

alter SESSION set NLS_DATE_FORMAT = 'DD.MM.YYYY HH24:MI:SS';

CREATE TABLE adresa (
    id_adresa       INTEGER NOT NULL,
    ulice           VARCHAR2(80),
    cislo_popisne   INTEGER NOT NULL,
    obec            VARCHAR2(80) NOT NULL,
    psc             INTEGER NOT NULL
);

ALTER TABLE adresa ADD CONSTRAINT adresa_pk PRIMARY KEY ( id_adresa );

CREATE TABLE boudar (
    id_zamestnanec               INTEGER NOT NULL,
    pracovni_zarazeni            VARCHAR2(80) NOT NULL,
    zodpovednost_za_objednavky   CHAR(1) NOT NULL,
    zodpovednost_za_penize       CHAR(1) NOT NULL
);

ALTER TABLE boudar ADD CONSTRAINT boudar_pk PRIMARY KEY ( id_zamestnanec );

CREATE TABLE dite (
    id_dite                INTEGER NOT NULL,
    jmeno                  VARCHAR2(80) NOT NULL,
    prijmeni               VARCHAR2(80) NOT NULL,
    rok_narozeni           INTEGER NOT NULL,
    vyska                  INTEGER NOT NULL,
    vaha                   INTEGER NOT NULL,
    aktualni_uroven        VARCHAR2(80),
    zakaznik_id_zakaznik   INTEGER NOT NULL
);

ALTER TABLE dite ADD CONSTRAINT dite_pk PRIMARY KEY ( id_dite,
                                                      zakaznik_id_zakaznik );

CREATE TABLE hodina_vyuky (
    id_hodina_vyuky          INTEGER NOT NULL,
    datum                    DATE NOT NULL,
    od                       VARCHAR2(80) NOT NULL,
    do                       VARCHAR2(80) NOT NULL,
    cena                     INTEGER NOT NULL,
    obj_vyuky_id_obj_vyuky   INTEGER NOT NULL
);

ALTER TABLE hodina_vyuky ADD CONSTRAINT hodina_vyuky_pk PRIMARY KEY ( id_hodina_vyuky,
                                                                      obj_vyuky_id_obj_vyuky );

CREATE TABLE hulky (
    id_hulky   INTEGER NOT NULL,
    znacka     VARCHAR2(80) NOT NULL,
    delka      INTEGER NOT NULL,
    prohnuti   CHAR(1) NOT NULL
);

ALTER TABLE hulky ADD CONSTRAINT hulky_pk PRIMARY KEY ( id_hulky );

CREATE TABLE instruktor (
    id_zamestnanec     INTEGER NOT NULL,
    co_uci             VARCHAR2(80) NOT NULL,
    uroven_kurzu       VARCHAR2(80) NOT NULL,
    velikost_munduru   VARCHAR2(80) NOT NULL
);

ALTER TABLE instruktor ADD CONSTRAINT instruktor_pk PRIMARY KEY ( id_zamestnanec );

CREATE TABLE instruktor_hodina (
    instr_id_zamestnanec     INTEGER NOT NULL,
    hod_vyuky_id_hod_vyuky   INTEGER NOT NULL,
    hod_vyuky_id_obj_vyuky   INTEGER NOT NULL
);

ALTER TABLE instruktor_hodina
    ADD CONSTRAINT instruktor_hodina_pk PRIMARY KEY ( instr_id_zamestnanec,
                                                      hod_vyuky_id_hod_vyuky,
                                                      hod_vyuky_id_obj_vyuky );

CREATE TABLE lyzarske_boty (
    id_lyzarske_boty      INTEGER NOT NULL,
    znacka                VARCHAR2(80) NOT NULL,
    model                 VARCHAR2(80) NOT NULL,
    flex                  INTEGER NOT NULL,
    velikost_normalni     INTEGER NOT NULL,
    velikost_pro_vazani   INTEGER NOT NULL
);

ALTER TABLE lyzarske_boty ADD CONSTRAINT lyzarske_boty_pk PRIMARY KEY ( id_lyzarske_boty );

CREATE TABLE lyze (
    id_lyze      INTEGER NOT NULL,
    znacka       VARCHAR2(80) NOT NULL,
    model        VARCHAR2(80) NOT NULL,
    delka        INTEGER NOT NULL,
    vazani_min   INTEGER NOT NULL,
    vazani_max   INTEGER NOT NULL,
    radius       VARCHAR2(80)
);

ALTER TABLE lyze ADD CONSTRAINT lyze_pk PRIMARY KEY ( id_lyze );

CREATE TABLE obj_vybaveni_dite (
    obj_vyb_id_obj_vyb   INTEGER NOT NULL,
    dite_id_dite         INTEGER NOT NULL,
    dite_id_zakaznik     INTEGER NOT NULL
);

ALTER TABLE obj_vybaveni_dite
    ADD CONSTRAINT obj_vybaveni_dite_pk PRIMARY KEY ( obj_vyb_id_obj_vyb,
                                                      dite_id_dite,
                                                      dite_id_zakaznik );

CREATE TABLE obj_vybaveni_hulky (
    obj_vyb_id_obj_vyb   INTEGER NOT NULL,
    hulky_id_hulky       INTEGER NOT NULL
);

ALTER TABLE obj_vybaveni_hulky ADD CONSTRAINT obj_vybaveni_hulky_pk PRIMARY KEY ( obj_vyb_id_obj_vyb,
                                                                                  hulky_id_hulky );

CREATE TABLE obj_vybaveni_lyz_boty (
    obj_vyb_id_obj_vyb               INTEGER NOT NULL,
    lyzarske_boty_id_lyzarske_boty   INTEGER NOT NULL
);

ALTER TABLE obj_vybaveni_lyz_boty ADD CONSTRAINT obj_vybaveni_lyz_boty_pk PRIMARY KEY ( obj_vyb_id_obj_vyb,
                                                                                        lyzarske_boty_id_lyzarske_boty );

CREATE TABLE obj_vybaveni_lyze (
    obj_vyb_id_obj_vyb   INTEGER NOT NULL,
    lyze_id_lyze         INTEGER NOT NULL
);

ALTER TABLE obj_vybaveni_lyze ADD CONSTRAINT obj_vybaveni_lyze_pk PRIMARY KEY ( obj_vyb_id_obj_vyb,
                                                                                lyze_id_lyze );

CREATE TABLE obj_vybaveni_prilba (
    prilba_id_prilba     INTEGER NOT NULL,
    obj_vyb_id_obj_vyb   INTEGER NOT NULL
);

ALTER TABLE obj_vybaveni_prilba ADD CONSTRAINT obj_vybaveni_prilba_pk PRIMARY KEY ( prilba_id_prilba,
                                                                                    obj_vyb_id_obj_vyb );

CREATE TABLE obj_vybaveni_snb (
    obj_vyb_id_obj_vyb   INTEGER NOT NULL,
    snb_id_snb           INTEGER NOT NULL
);

ALTER TABLE obj_vybaveni_snb ADD CONSTRAINT obj_vybaveni_snb_pk PRIMARY KEY ( obj_vyb_id_obj_vyb,
                                                                              snb_id_snb );

CREATE TABLE obj_vybaveni_snb_boty (
    obj_vyb_id_obj_vyb     INTEGER NOT NULL,
    snb_boty_id_snb_boty   INTEGER NOT NULL
);

ALTER TABLE obj_vybaveni_snb_boty ADD CONSTRAINT obj_vybaveni_snb_boty_pk PRIMARY KEY ( obj_vyb_id_obj_vyb,
                                                                                        snb_boty_id_snb_boty );

CREATE TABLE objednavka_vybaveni (
    id_objednavka_vybaveni   INTEGER NOT NULL,
    datum_a_cas_od           DATE NOT NULL,
    datum_a_cas_do           DATE NOT NULL,
    cena                     INTEGER NOT NULL
);

ALTER TABLE objednavka_vybaveni ADD CONSTRAINT objednavka_vybaveni_pk PRIMARY KEY ( id_objednavka_vybaveni );

CREATE TABLE objednavka_vyuky (
    id_objednavka_vyuky    INTEGER NOT NULL,
    predmet_vyuky          VARCHAR2(80) NOT NULL,
    uroven                 VARCHAR2(80) NOT NULL,
    zakaznik_id_zakaznik   INTEGER NOT NULL
);

ALTER TABLE objednavka_vyuky ADD CONSTRAINT objednavka_vyuky_pk PRIMARY KEY ( id_objednavka_vyuky );

CREATE TABLE prilba (
    id_prilba         INTEGER NOT NULL,
    znacka            VARCHAR2(80) NOT NULL,
    obvod_hlavy_min   INTEGER NOT NULL,
    obvod_hlavy_max   INTEGER NOT NULL
);

ALTER TABLE prilba ADD CONSTRAINT prilba_pk PRIMARY KEY ( id_prilba );

CREATE TABLE snowboard (
    id_snowboard   INTEGER NOT NULL,
    znacka         VARCHAR2(80) NOT NULL,
    model          VARCHAR2(80) NOT NULL,
    delka          INTEGER NOT NULL,
    typ_prohnuti   VARCHAR2(80) NOT NULL
);

ALTER TABLE snowboard ADD CONSTRAINT snowboard_pk PRIMARY KEY ( id_snowboard );

CREATE TABLE snowboardove_boty (
    id_snowboardove_boty   INTEGER NOT NULL,
    znacka                 VARCHAR2(80) NOT NULL,
    model                  VARCHAR2(80) NOT NULL,
    velikost               INTEGER NOT NULL
);

ALTER TABLE snowboardove_boty ADD CONSTRAINT snowboardove_boty_pk PRIMARY KEY ( id_snowboardove_boty );

CREATE TABLE zakaznik (
    id_zakaznik        INTEGER NOT NULL,
    jmeno              VARCHAR2(80) NOT NULL,
    prijmeni           VARCHAR2(80) NOT NULL,
    telefon            VARCHAR2(80) NOT NULL,
    email              VARCHAR2(80),
    adresa_id_adresa   INTEGER NOT NULL
);

ALTER TABLE zakaznik ADD CONSTRAINT zakaznik_pk PRIMARY KEY ( id_zakaznik );

CREATE TABLE zamestnanec (
    id_zamestnanec     INTEGER NOT NULL,
    jmeno              VARCHAR2(80) NOT NULL,
    prijmeni           VARCHAR2(80) NOT NULL,
    telefon            VARCHAR2(80) NOT NULL,
    email              VARCHAR2(80) NOT NULL,
    datum_nastupu      DATE NOT NULL,
    plat               INTEGER NOT NULL,
    adresa_id_adresa   INTEGER NOT NULL,
    zamestnanec_type   VARCHAR2(11) NOT NULL
);

ALTER TABLE zamestnanec
    ADD CONSTRAINT ch_inh_zamestnanec CHECK ( zamestnanec_type IN (
        'BOUDAR',
        'INSTRUKTOR',
        'ZAMESTNANEC'
    ) );

ALTER TABLE zamestnanec ADD CONSTRAINT zamestnanec_pk PRIMARY KEY ( id_zamestnanec );

ALTER TABLE boudar
    ADD CONSTRAINT boudar_zamestnanec_fk FOREIGN KEY ( id_zamestnanec )
        REFERENCES zamestnanec ( id_zamestnanec );

ALTER TABLE dite
    ADD CONSTRAINT dite_zakaznik_fk FOREIGN KEY ( zakaznik_id_zakaznik )
        REFERENCES zakaznik ( id_zakaznik );

ALTER TABLE hodina_vyuky
    ADD CONSTRAINT hod_vyuky_obj_vyuky_fk FOREIGN KEY ( obj_vyuky_id_obj_vyuky )
        REFERENCES objednavka_vyuky ( id_objednavka_vyuky );

ALTER TABLE instruktor_hodina
    ADD CONSTRAINT instruktor_hod_hod_vyuky_fk FOREIGN KEY ( hod_vyuky_id_hod_vyuky,
                                                             hod_vyuky_id_obj_vyuky )
        REFERENCES hodina_vyuky ( id_hodina_vyuky,
                                  obj_vyuky_id_obj_vyuky );

ALTER TABLE instruktor_hodina
    ADD CONSTRAINT instruktor_hod_instruktor_fk FOREIGN KEY ( instr_id_zamestnanec )
        REFERENCES instruktor ( id_zamestnanec );

ALTER TABLE instruktor
    ADD CONSTRAINT instruktor_zamestnanec_fk FOREIGN KEY ( id_zamestnanec )
        REFERENCES zamestnanec ( id_zamestnanec );

ALTER TABLE obj_vybaveni_dite
    ADD CONSTRAINT obj_vyb_dite_dite_fk FOREIGN KEY ( dite_id_dite,
                                                      dite_id_zakaznik )
        REFERENCES dite ( id_dite,
                          zakaznik_id_zakaznik );

ALTER TABLE obj_vybaveni_dite
    ADD CONSTRAINT obj_vyb_dite_obj_vyb_fk FOREIGN KEY ( obj_vyb_id_obj_vyb )
        REFERENCES objednavka_vybaveni ( id_objednavka_vybaveni );

ALTER TABLE obj_vybaveni_hulky
    ADD CONSTRAINT obj_vyb_hulky_hulky_fk FOREIGN KEY ( hulky_id_hulky )
        REFERENCES hulky ( id_hulky );

ALTER TABLE obj_vybaveni_hulky
    ADD CONSTRAINT obj_vyb_hulky_obj_vyb_fk FOREIGN KEY ( obj_vyb_id_obj_vyb )
        REFERENCES objednavka_vybaveni ( id_objednavka_vybaveni );

ALTER TABLE obj_vybaveni_lyz_boty
    ADD CONSTRAINT obj_vyb_lyz_boty_lyz_boty_fk FOREIGN KEY ( lyzarske_boty_id_lyzarske_boty )
        REFERENCES lyzarske_boty ( id_lyzarske_boty );

ALTER TABLE obj_vybaveni_lyz_boty
    ADD CONSTRAINT obj_vyb_lyz_boty_obj_vyb_fk FOREIGN KEY ( obj_vyb_id_obj_vyb )
        REFERENCES objednavka_vybaveni ( id_objednavka_vybaveni );

ALTER TABLE obj_vybaveni_lyze
    ADD CONSTRAINT obj_vyb_lyze_lyze_fk FOREIGN KEY ( lyze_id_lyze )
        REFERENCES lyze ( id_lyze );

ALTER TABLE obj_vybaveni_lyze
    ADD CONSTRAINT obj_vyb_lyze_obj_vyb_fk FOREIGN KEY ( obj_vyb_id_obj_vyb )
        REFERENCES objednavka_vybaveni ( id_objednavka_vybaveni );

ALTER TABLE obj_vybaveni_prilba
    ADD CONSTRAINT obj_vyb_prilba_obj_vyb_fk FOREIGN KEY ( obj_vyb_id_obj_vyb )
        REFERENCES objednavka_vybaveni ( id_objednavka_vybaveni );

ALTER TABLE obj_vybaveni_prilba
    ADD CONSTRAINT obj_vyb_prilba_prilba_fk FOREIGN KEY ( prilba_id_prilba )
        REFERENCES prilba ( id_prilba );

ALTER TABLE obj_vybaveni_snb_boty
    ADD CONSTRAINT obj_vyb_snb_boty_obj_vyb_fk FOREIGN KEY ( obj_vyb_id_obj_vyb )
        REFERENCES objednavka_vybaveni ( id_objednavka_vybaveni );

ALTER TABLE obj_vybaveni_snb_boty
    ADD CONSTRAINT obj_vyb_snb_boty_snb_boty_fk FOREIGN KEY ( snb_boty_id_snb_boty )
        REFERENCES snowboardove_boty ( id_snowboardove_boty );

ALTER TABLE obj_vybaveni_snb
    ADD CONSTRAINT obj_vyb_snb_obj_vyb_fk FOREIGN KEY ( obj_vyb_id_obj_vyb )
        REFERENCES objednavka_vybaveni ( id_objednavka_vybaveni );

ALTER TABLE obj_vybaveni_snb
    ADD CONSTRAINT obj_vyb_snb_snb_fk FOREIGN KEY ( snb_id_snb )
        REFERENCES snowboard ( id_snowboard );

ALTER TABLE objednavka_vyuky
    ADD CONSTRAINT objednavka_vyuky_zakaznik_fk FOREIGN KEY ( zakaznik_id_zakaznik )
        REFERENCES zakaznik ( id_zakaznik );

ALTER TABLE zakaznik
    ADD CONSTRAINT zakaznik_adresa_fk FOREIGN KEY ( adresa_id_adresa )
        REFERENCES adresa ( id_adresa );

ALTER TABLE zamestnanec
    ADD CONSTRAINT zamestnanec_adresa_fk FOREIGN KEY ( adresa_id_adresa )
        REFERENCES adresa ( id_adresa );

CREATE OR REPLACE TRIGGER arc_fkarc_2_instruktor BEFORE
    INSERT OR UPDATE OF id_zamestnanec ON instruktor
    FOR EACH ROW
DECLARE
    d VARCHAR2(11);
BEGIN
    SELECT
        a.zamestnanec_type
    INTO d
    FROM
        zamestnanec a
    WHERE
        a.id_zamestnanec = :new.id_zamestnanec;

    IF ( d IS NULL OR d <> 'INSTRUKTOR' ) THEN
        raise_application_error(-20223, 'FK INSTRUKTOR_ZAMESTNANEC_FK in Table INSTRUKTOR violates Arc constraint on Table ZAMESTNANEC - discriminator column ZAMESTNANEC_TYPE doesn''t have value ''INSTRUKTOR'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_2_boudar BEFORE
    INSERT OR UPDATE OF id_zamestnanec ON boudar
    FOR EACH ROW
DECLARE
    d VARCHAR2(11);
BEGIN
    SELECT
        a.zamestnanec_type
    INTO d
    FROM
        zamestnanec a
    WHERE
        a.id_zamestnanec = :new.id_zamestnanec;

    IF ( d IS NULL OR d <> 'BOUDAR' ) THEN
        raise_application_error(-20223, 'FK BOUDAR_ZAMESTNANEC_FK in Table BOUDAR violates Arc constraint on Table ZAMESTNANEC - discriminator column ZAMESTNANEC_TYPE doesn''t have value ''BOUDAR'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE SEQUENCE SEQ_ID_TMP START WITH 1 NOCACHE ORDER ;

