name: CI

on: push

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/setup.yaml
  docker_image:
    name: Docker Image
    needs: [setup]
    if: >-
      needs.setup.outputs.workflows != 'false' ||
      needs.setup.outputs.devcontainer != 'false'
    uses: ./.github/workflows/docker_image.yaml
    secrets: inherit
# verify pre commit hooks
# Code Style/C++
          # /Markdown https://github.com/markdownlint/markdownlint
          # /Python
# Build matrix per arch
# Docs (PA2)
# Test matrix per arch
  # - bi-zum-sudoku-csp
